# Generated by Django 4.1.5 on 2023-03-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_1', models.IntegerField(blank=True, null=True)),
                ('q1_2', models.CharField(blank=True, max_length=10, null=True)),
                ('q1_3', models.CharField(blank=True, max_length=50, null=True)),
                ('q2_1', models.BooleanField(blank=True, null=True)),
                ('q2_2', models.BooleanField(blank=True, null=True)),
                ('q2_3', models.BooleanField(blank=True, null=True)),
                ('q2_4', models.BooleanField(blank=True, null=True)),
                ('q3_1', models.CharField(blank=True, max_length=50, null=True)),
                ('q3_2', models.CharField(blank=True, max_length=50, null=True)),
                ('q3_3', models.CharField(blank=True, max_length=50, null=True)),
                ('q3_4', models.TextField(blank=True, null=True)),
                ('q3_5', models.TextField(blank=True, null=True)),
                ('q4_1', models.CharField(blank=True, max_length=50, null=True)),
                ('q4_2', models.BooleanField(blank=True, null=True)),
                ('q4_3', models.CharField(blank=True, max_length=100, null=True)),
                ('q4_4', models.BooleanField(blank=True, null=True)),
                ('q4_5', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
